src/Entity/Events.php
<?php

namespace App\Entity;

use App\Repository\EventsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Integer;

#[ORM\Entity(repositoryClass: EventsRepository::class)]
class Events
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $Discription = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $deadline = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $DateStart = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $DateEnd = null;

    #[ORM\Column(length: 255)]
    private ?string $Link = null;

    #[ORM\Column]
    private ?int $CheckValid = 0;

    #[ORM\Column]
    private ?int $CheckArchive = 0;

    #[ORM\Column]
    private ?int $id_user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDiscription(): ?string
    {
        return $this->Discription;
    }

    public function setDiscription(string $Discription): self
    {
        $this->Discription = $Discription;

        return $this;
    }

    public function getDeadline(): ?\DateTimeInterface
    {
        return $this->deadline;
    }

    public function setDeadline(\DateTimeInterface $deadline): self
    {
        $this->deadline = $deadline;

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->DateStart;
    }

    public function setDateStart(\DateTimeInterface $DateStart): self
    {
        $this->DateStart = $DateStart;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->DateEnd;
    }

    public function setDateEnd(\DateTimeInterface $DateEnd): self
    {
        $this->DateEnd = $DateEnd;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->Link;
    }

    public function setLink(string $Link): self
    {
        $this->Link = $Link;

        return $this;
    }

    public function getCheckValid(): ?int
    {
        return $this->CheckValid;
    }

    public function setCheckValid(int $CheckValid): self
    {
        $this->CheckValid = $CheckValid;

        return $this;
    }

    public function getCheckArchive(): ?int
    {
        return $this->CheckArchive;
    }

    public function setCheckArchive(int $CheckArchive): self
    {
        $this->CheckArchive = $CheckArchive;

        return $this;
    }

    public function getIdUser(): ?int
    {
        return $this->id_user;
    }

    public function setIdUser(int $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }
}

src/Form/EventsType.php
<?php

namespace App\Form;

use App\Entity\Events;
use Doctrine\DBAL\Types\DateTimeType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
class EventsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('Discription')
            ->add('deadline', DateType::class, [
                'widget' => 'single_text'])
            ->add('DateStart', DateType::class, [
                'widget' => 'single_text'])
            ->add('DateEnd', DateType::class, [
                'widget' => 'single_text'])
            ->add('Link')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Events::class,
        ]);
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Events;
use App\Entity\Participants;
use App\Entity\User;
use App\Form\EventsType;
use App\Repository\EventsRepository;
use App\Repository\ParticipantsRepository;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\UserRepository;
use DoctrineExtensions\Query\Mysql\Unserialize;

class HomeController extends AbstractController
{
    private $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

        /**
     * Check if the current user has joined a specific event.
     *
     * @param int $eventId
     * @return bool
     */
    private function hasUserJoinedEvent(int $eventId): bool
    {
        $user = $this->getUser();
        
        if ($user) {
            $userId = $user->getId();

            // Check if the user has joined the event
            $check = $this->em->createQueryBuilder()
                ->select('e')
                ->from(Participants::class, 'e')
                ->where('e.id_user = :userId')
                ->andWhere('e.id_event = :eventId')
                ->setParameter('userId', $userId)
                ->setParameter('eventId', $eventId);

            $queryCheck = $check->getQuery();
            $result = $queryCheck->getResult();

            return count($result) > 0;
        }

        return false;
    }

    #[Route('/home', name: 'app_home')]
    public function index(Request $request): Response
    {
        $user = $this->getUser();
        $id = $user->getId();
        $firstName = $user->getFirstName();
        $secondName = $user->getSecondName();
        $matricule = $user->getMatricule();

        $events = new Events();
        $events->setIdUser($id);
        $form = $this->createForm(EventsType::class, $events);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($events);
            $entityManager->flush();
            return $this->redirectToRoute('app_home');
        }

        // get current date
        $currentDate = new DateTime();
        $currentDate->setTime(0, 0, 0);

        // Find approved events
        $activated = $this->em->createQueryBuilder()
            ->select('e')
            ->from(Events::class, 'e')
            ->where('e.CheckValid = 1');
        $queryActive = $activated->getQuery();
        $active = $queryActive->getResult();



        $eventIdToCheck = 1;

        // check if the current user is joined the event or not
        $check = $this->em->createQueryBuilder()
            ->select('e')
            ->from(Participants::class, 'e')
            ->where('e.id_user = :userId')
            ->setParameter('userId', $id);

        $query_check = $check->getQuery();
        $check_done = $query_check->getResult();

        return $this->render('home/index.html.twig', [
            'id' => $id,
            'firstName' => $firstName,
            'secondName' => $secondName,
            'approved_event' => $active,
            'Today' => $currentDate,
            'mat' => $matricule,
            'check' => $check_done,
            'form' => $form->createView(),
            'eventIdToCheck' => $eventIdToCheck,
        ]);
    }


    #[Route('/home/addevent', name: 'addevent')]
    public function add_event(Request $request): Response
    {
        $user = $this->getUser();
        $id = $user->getId();
        $events = new Events();
        $events->setIdUser($id);
        $form = $this->createForm(EventsType::class, $events);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($events);
            $entityManager->flush();

            return $this->redirectToRoute('app_home');
        }
        return $this->render('home/Events/add.html.twig', [
            'calendar' => $events,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/home/add_participant', name: 'add_participant')]
    public function add_participant(Request $request,Session $session): Response
    {
        $session->getFlashBag()->add('success', 'Joined');

        $id_event = $request->query->get('id_event');
        $id_user = $request->query->get('id_user');
        $user_matricule = $request->query->get('user_matricule');

        $participant = new Participants();
        $participant->setIdUser($id_user);
        $participant->setIdEvent($id_event);
        $participant->setUserMatricule($user_matricule);

        $entityManager = $this->getDoctrine()->getManager();

        $entityManager->persist($participant);

        $entityManager->flush();

        return $this->redirectToRoute('app_home');
    }

    #[Route('/home/participant/Events/{identidfiant}', name: 'app_home_part_show', methods: 'GET')]
    public function participant_display(UserRepository $userRepository,EventsRepository $eventsRepository,ParticipantsRepository $participantsRepository,int $identidfiant): Response
    {
        $event_number = $identidfiant;
        $user = $this->getUser();
        $id = $user->getId();
        $firstName = $user->getFirstName();
        $secondName = $user->getSecondName();

        //find selected event to display
        $entityManager = $this->getDoctrine()->getManager();

        $item = $entityManager->getRepository(Participants::class)->find($identidfiant);

        //find the user who sugg the event
        $participant = $this->em->createQueryBuilder()
            ->select('u')
            ->from(User::class, 'u')
            ->innerJoin(Participants::class,'e','WITH','e.id_user = u.id')
            ->andWhere('e.id_event = :identidfiant')
            ->setParameter('identidfiant', $identidfiant)
            ->getQuery();
        $part_result = $participant->getResult();

        return $this->render('home/Participants/show.html.twig', [
            'id'=>$id,
            'firstName' => $firstName,
            'secondName' => $secondName,
            'part_of_event'=>$part_result,
            'event_number'=>$event_number,

        ]);

    }

    #[Route('/home/Event/display/{identidfiant}', name: 'app_home_display', methods: 'GET')]
    public function event_home_displays(UserRepository $userRepository,EventsRepository $eventsRepository,int $identidfiant): Response
    {
        $user = $this->getUser();
        $id = $user->getId();
        $firstName = $user->getFirstName();
        $secondName = $user->getSecondName();
        $currentDate = new DateTime();
        $currentDate->setTime(0, 0, 0);

        //find selected event to display
        $entityManager = $this->getDoctrine()->getManager();

        $item = $entityManager->getRepository(Events::class)->find($identidfiant);


        // render the template and pass the first name to it
        return $this->render('home/Events/display.html.twig', [
            'firstName' => $firstName,
            'secondName' => $secondName,
            'Today'=>$currentDate,
            'id'=>$id,
            'displayitem'=>$item,
        ]);

    }


    #[Route('/remove_event', name: 'delete_event')]
    public function delete_event(Request $request,Session $session): Response
    {
        $session->getFlashBag()->add('danger', 'Event Deleted With Success');

        $id = $request->query->get('id');

        $entityManager = $this->getDoctrine()->getManager();

        $myEntity = $entityManager->getRepository(Events::class)->find($id);

        $entityManager->remove($myEntity);
        $entityManager->flush();

        return $this->redirectToRoute('app_admin_details');
    }

    #[Route('/validate', name: 'validate_event')]
    public function validate(Request $request,Session $session): Response
    {
        $session->getFlashBag()->add('success', 'Event Approved');

        $id = $request->query->get('id');

        $entityManager = $this->getDoctrine()->getManager();

        $myEntity = $entityManager->getRepository(Events::class)->find($id);

        $myEntity->setCheckValid(1);

        $entityManager->flush();

        return $this->redirectToRoute('app_admin_details');
    }

    #[Route('/dis-activate', name: 'changeActivationStat')]
    public function No_activate(Request $request,Session $session): Response
    {
        $id = $request->query->get('id');

        $entityManager = $this->getDoctrine()->getManager();

        $myEntity = $entityManager->getRepository(User::class)->find($id);

        $myEntity->setActive(0);

        $entityManager->flush();

        return $this->redirectToRoute('app_logout');
    }

    #[Route('/put_to_archive', name: 'archive_event')]
    public function arch(Request $request,Session $session): Response
    {
        $session->getFlashBag()->add('danger', 'Event Archived');

        $id = $request->query->get('id');

        $entityManager = $this->getDoctrine()->getManager();

        $myEntity = $entityManager->getRepository(Events::class)->find($id);

        $myEntity->setCheckArchive(1);

        $entityManager->flush();

        return $this->redirectToRoute('app_admin_details');
    }

    #[Route('/out_of_archive', name: 'unarchive_event')]
    public function unarch(Request $request,Session $session): Response
    {
        $session->getFlashBag()->add('success', 'Event Unarchived');

        $id = $request->query->get('id');

        $entityManager = $this->getDoctrine()->getManager();

        $myEntity = $entityManager->getRepository(Events::class)->find($id);

        $myEntity->setCheckArchive(0);

        $entityManager->flush();

templates/home/Events/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HomeController!{% endblock %}

{% block body %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}
{% endblock %}

templates/home/Events/display.html.twig
{% extends 'home/base.html.twig' %}
{% block body %}
<!-- dropzone css -->
<link href="{{ asset("libs/dropzone/min/dropzone.min.css") }}" rel="stylesheet" type="text/css" />

<!-- flatpickr css -->
<link href="{{ asset("libs/flatpickr/flatpickr.min.css") }}" rel="stylesheet" type="text/css">
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div>
                    <ul class="wizard-nav mb-5">
                        <li class="wizard-list-item">
                            <div class="list-item">
                                <div class="step-icon" data-bs-toggle="tooltip" data-bs-placement="top"
                                     title="Basic Info">
                                    <i class="fa-solid fa-1"></i>
                                </div>
                            </div>
                        </li>
                        <li class="wizard-list-item">
                            <div class="list-item">
                                <div class="step-icon" data-bs-toggle="tooltip" data-bs-placement="top"
                                     title="Assignee">
                                    <i class="fa-solid fa-2"></i>
                                </div>
                            </div>
                        </li>

                        <li class="wizard-list-item">
                            <div class="list-item">
                                <div class="step-icon" data-bs-toggle="tooltip" data-bs-placement="top"
                                     title="Attached Files">
                                    <i class="fa-solid fa-3"></i>
                                </div>
                            </div>
                        </li>
                    </ul>
                    <!-- wizard-nav -->


                    <div class="wizard-tab">
                        <div class="text-center mb-4">
                            <h5>Event Information</h5>
                            <p class="card-title-desc">N°{{ displayitem.id }}</p>
                        </div>
                        <form>
                            <div>
                                <div class="mb-3">
                                    <label for="projectname" class="form-label">Event Title</label>
                                    <input id="projectname" type="text" class="form-control" value="{{ displayitem.title }}" disabled>
                                </div>

                                <div class="mb-3">
                                    <label for="projectdesc" class="form-label">Project Description</label>
                                    <textarea class="form-control" id="projectdesc" rows="3"  disabled>{{ displayitem.discription }}</textarea>
                                </div>
                                <div class="mb-3">
                                    <label class="form-label">DeadLine</label>
                                    <input type="text" class="form-control" id="datepicker-range" value="{{ displayitem.deadline|date('Y-m-d') }}" disabled>
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- wizard-tab -->

                    <div class="wizard-tab">
                        <div class="text-center mb-4">
                            <h5>Event Dates</h5>
                            <p class="card-title-desc">Start & End</p>
                        </div>
                        <form>
                            <div>
                                <div class="mb-3">
                                    <label class="form-label">Start Date</label>
                                    <input type="text" class="form-control" id="datepicker-range" value="{{ displayitem.DateStart|date('Y-m-d') }}" disabled>
                                </div>
                                <div class="mb-3">
                                    <label class="form-label">End Date</label>
                                    <input type="text" class="form-control" id="datepicker-range" value="{{ displayitem.DateEnd|date('Y-m-d') }}" disabled>
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- wizard-tab -->

                    <div class="wizard-tab">
                        <div class="text-center mb-4">
                            <h5>Event Link</h5>
                        </div>
                        <div class="mb-3">
                            <label for="projectname" class="form-label">Event Link</label>
                            <input id="projectname" type="text" class="form-control" value="{{ displayitem.link }}" disabled>
                        </div>
                    </div>
                    <div class="d-flex align-items-start gap-3 mt-4">
                        <button type="button" class="btn btn-primary w-sm" id="prev">Previous</button>
                        <button type="button" class="btn btn-primary w-sm ms-auto" id="next" >Next</button>
                    </div>
                </div>
            </div><!-- end card body -->
        </div><!-- end card -->
    </div><!-- end col -->
</div><!-- end row -->
<!-- flatpickr js -->
<script src="{{ asset("libs/flatpickr/flatpickr.min.js") }}"></script>

<!-- dropzone plugin -->
<script src="{{ asset("libs/dropzone/min/dropzone.min.js") }}"></script>

<!-- init js -->
<script src="{{ asset("js/pages/project-create.init.js") }}"></script>

<script src="{{ asset("assets/js/app.js") }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(document).ready(function() {
        var currentTab = 0;
        $("#next").click(function() {
            $(".wizard-tab:eq(" + currentTab + ")").hide();
            currentTab++;
            if (currentTab >= $(".wizard-tab").length) {
                currentTab = 0;
            }
            $(".wizard-tab:eq(" + currentTab + ")").show();
        });
        $("#prev").click(function() {
            $(".wizard-tab:eq(" + currentTab + ")").hide();
            currentTab--;
            if (currentTab < 0) {
                currentTab = $(".wizard-tab").length - 1;
            }
            $(".wizard-tab:eq(" + currentTab + ")").show();
        });

    });
</script>
{% endblock %}